appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: APm9Vir2EZ6PeI0ln03MtAlfBJ+LRur1obdqfOXn68xhk1fELm5uRAks8Se7Ca6C1CQ80JyVbhLc/C95Yfnp52oh2r+MKzCnH+ZAE2QRBFJJUemc2gnEdWU5hTC/+YEkKA0EPk2zujfMkv26CmJfFlQ2t/MfPa8NX1BufgbMSDYn7VtYkLqJFfIxoxxj+OG7oy0KQkPOEQ+NIF5BXXIrWrtwCb2oYepsvGTGDrnUjw/IJZzd7E7emvAMYDNriWx3mm38y8dgFuku0+Cm6zzTglT98lRlyZcNGPuj5ZhFjhmwu96N/CF5Q0N1UahRU+ahDwh0wM9OwHw/51SVHjsEmqq7gVHmwzQ2kmvIjQG6lTiB6uJexy424tfCPEmFtlvkhq1dbc3XeMycfiPNe88wiWHahmo6nrcJZ0JLNkWzOPfsdJYvxizI2YlhYrJNQta0AfcnBIOIJNopTSM86qP2BntNBQbgfkucjQ9DHWlI5dedx+2Juv2l0DLdtXFkeBQo54u2GQNCXDZVLrQ5gHiFD5aTzzBOAUtUqXqmtLX0RJ3ETwSe4ivCT3ufxJrUTQIHfNCvzk5hDF32F0j0JcOP2qpi1YkWl3K6OZjJn4Ifal5N+uCwbVgptzyVmwUWsfV4NLY4YMqX+RL0VA+ypea7aeDLIgIEfJYbN/SYmEbmfDE=}
